// Styles for the Services screen — extracted from services.tsx for readability.
// Pure static StyleSheet; no behavior, referenced via `import { styles }`.
import { StyleSheet } from "react-native";
import { C, RADIUS, SP, COMP } from "../../theme/tokens";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.gray100 },
  endOfList: {
    marginTop: SP._10, marginBottom: SP._10, fontSize: 12, fontWeight: "600",
    color: C.gray300, textAlign: "center",
  },

  searchRow: {
    backgroundColor: C.white,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.gray100,
    gap: 10,
  },
  statusFilterRow: {
    flexDirection: "row",
    gap: 6,
  },
  statusFilterTab: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: RADIUS.full,
    backgroundColor: C.gray100,
  },
  statusFilterTabActive: {
    backgroundColor: C.brand500,
  },
  statusFilterTabText: {
    fontSize: 12,
    fontWeight: "600",
    color: C.gray600,
  },
  statusFilterTabTextActive: {
    color: C.white,
  },

  // Category filter chips
  categoryFilterRow: { flexDirection: "row", gap: 6, paddingTop: 8 },
  categoryFilterChip: {
    paddingHorizontal: 12, paddingVertical: 6,
    borderRadius: RADIUS.full, backgroundColor: C.gray100,
    borderWidth: 1, borderColor: C.gray200,
  },
  categoryFilterChipActive: { backgroundColor: C.brand500, borderColor: C.brand500 },
  categoryFilterChipText: { fontSize: 12, fontWeight: "600", color: C.gray600 },
  categoryFilterChipTextActive: { color: C.white },

  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.white,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: C.gray200,
    paddingHorizontal: 12,
    height: 40,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: C.gray900,
    paddingVertical: 0,
  },

  scroll: { flex: 1, backgroundColor: C.gray100 },
  content: { padding: 16, paddingBottom: 100, alignItems: "center" },
  contentInner: { maxWidth: 880, width: "100%" },
  loadingBox: { height: 200, alignItems: "center", justifyContent: "center" },
  emptyBox: { alignItems: "center", paddingVertical: 56, paddingHorizontal: 32 },
  emptyIllustration: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: C.gray100,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  emptyTitle: { fontSize: 17, fontWeight: "700", color: C.gray900, marginBottom: 8, textAlign: "center" },
  emptyDesc: { fontSize: 13, color: C.gray500, textAlign: "center", lineHeight: 20, maxWidth: 260 },
  emptyAction: {
    marginTop: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: C.brand500,
    paddingHorizontal: 24,
    paddingVertical: 13,
    borderRadius: RADIUS.lg,
  },
  emptyActionText: { fontSize: 14, fontWeight: "600", color: C.white },

  /* Featured Section */
  featuredSection: { marginBottom: 20 },
  featuredLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
  },
  featuredBadge: {
    backgroundColor: C.warning100,
    borderRadius: RADIUS.full,
    padding: 4,
  },
  featuredLabelText: {
    fontSize: 12,
    fontWeight: "700",
    color: C.gray900,
    textTransform: "uppercase",
  },
  featuredScroll: { flexGrow: 0 },
  featuredContent: { gap: 10, paddingRight: 6 },
  featuredCard: {
    minWidth: 150,
    borderRadius: RADIUS.md,
    backgroundColor: C.white,
    padding: SP._12,
    borderWidth: 1.5,
    borderColor: C.warning300,
  },
  featuredCardName: { fontSize: 13, fontWeight: "700", color: C.gray900, marginBottom: 6 },
  featuredCardPrice: { fontSize: 14, fontWeight: "800", color: C.brand700, marginBottom: 4 },
  featuredCardUnit: { fontSize: 11, color: C.gray500, fontWeight: "400" },
  featuredCardMargin: { fontSize: 11, color: C.gray500 },

  /* Category Section */
  categoryGroup: { marginBottom: 18 },
  categoryHeader: {
    fontSize: 11,
    fontWeight: "700",
    color: C.gray500,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
  },

  /* Category dot */
  catDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
  },

  /* Service Card */
  serviceCard: {
    borderRadius: RADIUS.md,
  },
  serviceCardTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  serviceCardLeft: { flex: 1 },
  serviceCardName: { fontSize: 14, fontWeight: "700", color: C.gray900, marginBottom: 4 },
  serviceCardMeta: { flexDirection: "row", alignItems: "center", gap: 6 },
  serviceCardPrice: { fontSize: 13, fontWeight: "700", color: C.gray900 },
  serviceCardMetaDot: { fontSize: 11, color: C.gray400 },
  serviceCardUnit: { fontSize: 11, color: C.gray500, fontWeight: "400" },
  serviceCardCost: { fontSize: 11, color: C.gray500, fontWeight: "400" },
  serviceMarginText: { fontSize: 11, fontWeight: "600" },
  marginChip: {
    borderRadius: RADIUS.md,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignSelf: "flex-start",
  },
  marginChipText: { fontSize: 12, fontWeight: "700" },

  /* Archived Section */
  archivedSection: { marginTop: 20 },
  archivedToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 0,
  },
  archivedToggleText: { fontSize: 14, fontWeight: "700", color: C.gray900 },
  archivedServiceCard: { borderRadius: RADIUS.md },
  archivedServiceTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  archivedServiceName: { fontSize: 13, fontWeight: "700", color: C.gray700, marginBottom: 2 },
  archivedServiceDate: { fontSize: 11, color: C.gray500 },
  restoreBtn: { fontSize: 12, fontWeight: "700", color: C.success700 },

  /* Modal — tablet centering */
  tabletOverlay: {
    flex: 1, backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center", justifyContent: "center", padding: 32,
  },
  tabletCard: {
    width: "100%", maxWidth: 620, height: "86%",
    backgroundColor: C.white, borderRadius: RADIUS.xl, overflow: "hidden",
  },
  /* Modal */
  modalSafe: { flex: 1, backgroundColor: C.white },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: C.gray100,
  },
  modalClose: { padding: 4 },
  modalTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "700",
    color: C.gray900,
  },
  modalSaveBtn: {
    ...COMP.pillBtn,
    minWidth: 64,
  },
  modalSaveBtnText: { ...COMP.pillBtnText },
  modalScroll: { flex: 1 },
  // Generous bottom padding so the last field (Notes) can scroll clear of the
  // keyboard instead of being hidden behind it.
  modalContent: { padding: 20, paddingBottom: 240, alignItems: "center" },
  modalFormInner: { maxWidth: 760, width: "100%" },
  modalFooter: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: C.gray100,
    alignItems: "center",
  },
  modalFooterInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    maxWidth: 760,
    width: "100%",
  },
  modalCancelBtn: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: C.gray200,
    alignItems: "center",
    justifyContent: "center",
  },
  modalCancelBtnText: { fontSize: 14, fontWeight: "500", color: C.gray600 },
  modalAddBtn: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: RADIUS.md,
    backgroundColor: C.brand500,
    alignItems: "center",
    justifyContent: "center",
  },
  modalAddBtnText: { fontSize: 14, fontWeight: "600", color: C.white },

  archiveBtn: {
    alignItems: "center",
    paddingVertical: 14,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: C.gray100,
  },
  archiveBtnText: {
    fontSize: 13,
    fontWeight: "500",
    color: C.error500,
  },
  archiveOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  archiveOverlayNoDim: {
    backgroundColor: "transparent",
  },
  archiveDialog: {
    backgroundColor: C.white,
    borderRadius: RADIUS.xl,
    padding: 28,
    width: "100%",
    maxWidth: 400,
    alignItems: "center",
  },
  archiveIconBadge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: C.warning100,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  archiveDialogTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: C.gray900,
    marginBottom: 10,
    textAlign: "center",
  },
  archiveDialogDesc: {
    fontSize: 14,
    color: C.gray500,
    textAlign: "center",
    lineHeight: 21,
    marginBottom: 24,
  },
  archiveDialogActions: {
    flexDirection: "row",
    gap: 10,
    width: "100%",
  },
  archiveDialogCancel: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: RADIUS.lg,
    borderWidth: 1.5,
    borderColor: C.gray200,
    alignItems: "center",
  },
  archiveDialogCancelText: {
    fontSize: 14,
    fontWeight: "600",
    color: C.brand600,
  },
  archiveDialogConfirm: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: RADIUS.lg,
    backgroundColor: C.error500,
    alignItems: "center",
  },
  archiveDialogConfirmText: {
    fontSize: 14,
    fontWeight: "700",
    color: C.white,
  },

  fieldLabel: { ...COMP.fieldLabel },
  fieldInput: { ...COMP.field as any },
  fieldInputFocused: { ...COMP.fieldFocused as any },
  fieldInputError: { borderColor: C.error500, backgroundColor: "#fff5f5" },
  fieldHint: { fontSize: 11, color: C.gray500, marginTop: 4 },
  fieldErrorText: { fontSize: 11, color: C.error500, marginTop: 4 },
  requiredNote: { fontSize: 11, color: C.gray400, marginBottom: 14, fontStyle: "italic" as const },

  /* Category Chips */
  catChip: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: RADIUS.full,
    backgroundColor: C.gray100,
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  catChipActive: { backgroundColor: C.brand100, borderColor: C.brand500 },
  catChipText: { fontSize: 12, fontWeight: "600", color: C.gray600 },
  catChipTextActive: { color: C.brand700 },

  /* Unit Chips */
  unitChipsRow: { flexDirection: "row", gap: 8, marginBottom: 16, flexWrap: "wrap" },
  unitChip: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: RADIUS.full,
    backgroundColor: C.gray100,
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  unitChipActive: { backgroundColor: C.brand100, borderColor: C.brand500 },
  unitChipText: { fontSize: 12, fontWeight: "600", color: C.gray600 },
  unitChipTextActive: { color: C.brand700 },

  /* Margin Preview Badge */
  marginPreviewBadge: {
    backgroundColor: C.success100,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: C.success100,
  },
  marginPreviewBadgeText: { fontSize: 13, fontWeight: "700", color: C.success700 },
  marginPreviewSub: { fontSize: 11, fontWeight: "600", color: C.success700, opacity: 0.8, marginTop: 1 },

  /* Type toggle — segmented control */
  typeToggleContainer: {
    flexDirection: "row",
    backgroundColor: C.gray100,
    borderRadius: RADIUS.md,
    padding: 3,
    marginBottom: 4,
  },
  typeSegment: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: RADIUS.sm,
    alignItems: "center",
  },
  typeSegmentActive: {
    backgroundColor: C.white,
    shadowColor: C.gray900,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  typeSegmentText:       { fontSize: 13, fontWeight: "600", color: C.gray500 },
  typeSegmentTextActive: { fontSize: 13, fontWeight: "700", color: C.brand700 },

  modalSectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: C.gray500,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 6,
    marginTop: 8,
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: C.gray100,
  },
  switchRowFeatured: {
    backgroundColor: "#FEFCE8",
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    borderTopWidth: 0,
    marginTop: 4,
  },
  switchLabelRow: { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 2 },
  switchLabel: { fontSize: 14, fontWeight: "700", color: C.gray900 },
  switchLabelFeatured: { color: C.warning700 },
  switchHint: { fontSize: 12, color: C.gray600, marginTop: 2, lineHeight: 17 },

  /* Inventory usage */
  invEmptyHint: {
    fontSize: 12,
    color: C.gray500,
    textAlign: "center",
    padding: SP._12,
    backgroundColor: C.gray100,
    borderRadius: RADIUS.md,
    marginBottom: SP._8,
  },
  invContainer: {
    backgroundColor: C.gray50,
    borderRadius: RADIUS.md,
    padding: SP._12,
    marginBottom: SP._8,
    gap: 0,
  },
  invSectionHint: {
    fontSize: 12,
    color: C.gray500,
    lineHeight: 17,
    marginBottom: SP._10,
  },
  invPreview: {
    fontSize: 11,
    color: C.brand600,
    fontWeight: "500",
    marginTop: SP._6,
  },
  invRow: {
    borderRadius: RADIUS.sm,
    backgroundColor: C.white,
    padding: SP._12,
    marginBottom: SP._8,
  },
  invRowMain: { flexDirection: "row", alignItems: "center", gap: SP._8 },
  invQtyPerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SP._8,
    marginTop: SP._8,
  },
  invQtyGroup: { flexDirection: "row", alignItems: "center", gap: 4 },
  invUnitLabel: { fontSize: 12, fontWeight: "600", color: C.gray500 },
  invProductBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: RADIUS.md,
    paddingHorizontal: SP._10,
    paddingVertical: 8,
    backgroundColor: C.white,
    gap: SP._4,
  },
  invProductBtnText: { fontSize: 12, fontWeight: "600", color: C.gray900, flex: 1 },
  invQtyInput: {
    width: 56,
    borderRadius: RADIUS.md,
    paddingHorizontal: SP._8,
    paddingVertical: 8,
    fontSize: 13,
    color: C.gray900,
    textAlign: "center",
    backgroundColor: C.white,
  },
  invProductPicker: {
    borderRadius: RADIUS.md,
    backgroundColor: C.gray100,
    marginTop: SP._6,
    overflow: "hidden",
  },
  invPickerItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SP._12,
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: C.gray200,
  },
  invPickerItemActive: { backgroundColor: C.brand50 },
  invPickerItemText:   { fontSize: 12, color: C.gray700 },
  invSubLabel: { fontSize: 11, color: C.gray400, fontWeight: "500", alignSelf: "center" },
  invMiniChip: {
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
    backgroundColor: C.white,
  },
  invMiniChipActive:     { backgroundColor: C.brand500 },
  invMiniChipText:       { fontSize: 11, fontWeight: "500", color: C.gray500 },
  invMiniChipTextActive: { color: C.white, fontWeight: "600" },
  invAddRowBtn: {
    alignItems: "center",
    paddingVertical: SP._10,
    marginTop: SP._4,
    borderTopWidth: 1,
    borderTopColor: C.gray100,
  },
  invAddRowBtnText: { fontSize: 13, fontWeight: "600", color: C.brand600 },

  /* Filter group labels (Status / Type filter rows) */
  filterGroup: { gap: 6 },
  filterGroupLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: C.gray400,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  /* SelectField dropdown */
  selectBtn: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  selectBtnText: { fontSize: 14, color: C.gray900, flex: 1 },
  selectDropdown: {
    borderRadius: RADIUS.md,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.gray200,
    marginTop: 4,
    overflow: "hidden",
    shadowColor: C.gray900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  selectOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.gray100,
  },
  selectOptionActive: { backgroundColor: C.brand50 },
  selectOptionText: { fontSize: 14, color: C.gray700 },
  selectOptionTextActive: { color: C.brand700, fontWeight: "700" },

  /* Modal header spacer — mirrors close button width for centered title */
  modalHeaderSpacer: { width: 26 },

  /* Settings card — wraps Visibility / Stock toggle groups */
  settingsCard: {
    backgroundColor: C.gray50,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: C.gray100,
    overflow: "hidden",
    marginBottom: 16,
  },
  settingsCardRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderTopWidth: 1,
    borderTopColor: C.gray100,
  },
  settingsCardRowFirst: {
    borderTopWidth: 0,
  },

  // ── Online commission breakdown ────────────────────────────────────────────
  feeCard: {
    backgroundColor: C.brand50,
    borderWidth: 1,
    borderColor: C.brand100,
    borderRadius: RADIUS.md,
    padding: 12,
    marginBottom: 16,
  },
  feeCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  feeCardTitle: { fontSize: 13, fontWeight: "800", color: C.brand700 },
  feeCardNote: {
    fontSize: 11,
    color: C.brand700,
    opacity: 0.8,
    marginTop: 6,
    lineHeight: 16,
  },
  feeLineRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 3,
  },
  feeLineLabel: { fontSize: 13, color: C.gray700 },
  feeLineLabelStrong: { fontWeight: "800", color: C.gray900 },
  feeLineValue: { fontSize: 13, fontWeight: "700", color: C.gray800 },
  feeLineValueStrong: { fontSize: 15, fontWeight: "800", color: C.brand700 },
  feeLineMuted: { color: C.gray500 },
});
