const { withAndroidManifest, withInfoPlist } = require("@expo/config-plugins");

// Package visibility for the rider's "Preferred navigation" setting.
//
// Android 11+ (API 30) hides other installed apps unless they're declared in
// <queries>. Expo's generated manifest only declares the https scheme, so a
// waze:// or geo: link can't be resolved even when the app IS installed —
// Linking.openURL rejects and openMaps() silently falls back to Google, which
// looks exactly like the preference being ignored.
//
// iOS has the same idea under a different name: canOpenURL returns false for any
// scheme not listed in LSApplicationQueriesSchemes.
//
// AndroidManifest.xml and Info.plist are both regenerated by prebuild, so this
// has to be a plugin rather than a hand edit.
const SCHEMES = ["waze", "geo", "google.navigation", "comgooglemaps"];

const withNavAppQueries = (config) => {
  config = withAndroidManifest(config, (config) => {
    const manifest = config.modResults.manifest;
    manifest.queries = manifest.queries ?? [];
    // Expo emits a single <queries> element; append into it rather than adding
    // a second one, which the manifest merger rejects.
    const queries = manifest.queries[0] ?? {};
    if (!manifest.queries.length) manifest.queries.push(queries);
    queries.intent = queries.intent ?? [];

    for (const scheme of SCHEMES) {
      const already = queries.intent.some(
        (i) => i?.data?.[0]?.$?.["android:scheme"] === scheme,
      );
      if (already) continue;
      queries.intent.push({
        action: [{ $: { "android:name": "android.intent.action.VIEW" } }],
        data: [{ $: { "android:scheme": scheme } }],
      });
    }
    return config;
  });

  config = withInfoPlist(config, (config) => {
    const existing = config.modResults.LSApplicationQueriesSchemes ?? [];
    config.modResults.LSApplicationQueriesSchemes = [
      ...new Set([...existing, ...SCHEMES]),
    ];
    return config;
  });

  return config;
};

module.exports = withNavAppQueries;
