import React, { useState, useCallback, useEffect, useRef } from "react";
import { errField } from "../src/utils/userError";
import { View, Text, TextInput, TouchableOpacity, ScrollView, KeyboardAvoidingView, ActivityIndicator, Image, InteractionManager } from "react-native";
import type { KeyboardTypeOptions } from "react-native";
import { showAlert } from "../src/lib/dialog";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";
import { router, useFocusEffect } from "expo-router";
import { useAuth } from "../src/hooks/useAuth";
import { useBiometricAuth } from "../src/hooks/useBiometricAuth";
import { useResponsive } from "../src/hooks/useResponsive";
import { LoadingOverlay } from "../src/components/LoadingOverlay";
import { ResponsivePage } from "../src/components/ResponsivePage";
import { C } from "../src/theme/tokens";
import { S } from "../src/styles/loginStyles";
import { z } from "zod";
import { loginSchema } from "../src/lib/validation";
import Svg, { Path } from "react-native-svg"; // kept for the multicolor Google brand mark
import { Ionicons, MaterialCommunityIcons } from "@expo/vector-icons";
import gitRev from "../gitRev.json";

const LOGO = require("../assets/splash-icon.png");
// Build-stamped version from gitRev.json (regenerated by bash.sh at build time)
const APP_VERSION = gitRev.version;

// ── Icons ────────────────────────────────────────────────────────────────────

const I = {
  Eye: ({ visible, c = C.gray400 }: Readonly<{ visible: boolean; c?: string }>) => (
    <Ionicons name={visible ? "eye-off-outline" : "eye-outline"} size={20} color={c} />
  ),

  Check: ({ size = 12, color = C.white }: Readonly<{ size?: number; color?: string }>) => (
    <Ionicons name="checkmark" size={size} color={color} />
  ),

  Package: ({ c = "rgba(255,255,255,0.9)" }: Readonly<{ c?: string }>) => (
    <MaterialCommunityIcons name="cube-outline" size={18} color={c} />
  ),

  Google: () => (
    <Svg width={20} height={20} viewBox="0 0 48 48">
      <Path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"/>
      <Path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"/>
      <Path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"/>
      <Path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.18 1.48-4.97 2.31-8.16 2.31-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"/>
    </Svg>
  ),

  Apple: () => (
    <Svg width={20} height={20} viewBox="0 0 24 24">
      <Path
        fill={C.gray900}
        d="M17.05 20.28c-.98.95-2.05.8-3.08.35-1.09-.46-2.09-.48-3.24 0-1.44.62-2.2.44-3.06-.35C2.79 15.25 3.51 7.59 9.05 7.31c1.35.07 2.29.74 3.08.8 1.18-.24 2.31-.93 3.57-.84 1.51.12 2.65.72 3.4 1.8-3.12 1.87-2.38 5.98.48 7.13-.57 1.5-1.31 2.99-2.53 4.08zM12.03 7.25c-.15-2.23 1.66-4.07 3.74-4.25.29 2.58-2.34 4.5-3.74 4.25z"
      />
    </Svg>
  ),

  Receipt: ({ c = "rgba(255,255,255,0.9)" }: Readonly<{ c?: string }>) => (
    <Ionicons name="receipt-outline" size={18} color={c} />
  ),

  FaceId: ({ c = C.brand500 }: Readonly<{ c?: string }>) => (
    <MaterialCommunityIcons name="face-recognition" size={22} color={c} />
  ),

  Fingerprint: ({ c = C.brand500 }: Readonly<{ c?: string }>) => (
    <Ionicons name="finger-print" size={22} color={c} />
  ),
};

// ── Mini stat card (tablet left panel) ───────────────────────────────────────

function StatCard({ icon, label, value, small }: { icon: React.ReactNode; label: string; value: string; small?: boolean }) {
  return (
    <View style={[S.statCard, small && S.statCardSmall]}>
      <View style={[S.statIcon, small && S.statIconSmall]}>{icon}</View>
      <View style={S.statInfo}>
        <Text style={[S.statValue, small && S.statValueSmall]}>{value}</Text>
        <Text style={[S.statLabel, small && S.statLabelSmall]}>{label}</Text>
      </View>
    </View>
  );
}


// ── Field ─────────────────────────────────────────────────────────────────────

const Field = React.forwardRef<TextInput, {
  label: string;
  labelRight?: React.ReactNode;
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  keyboardType?: KeyboardTypeOptions;
  secure?: boolean;
  showToggle?: boolean;
  onToggleSecure?: () => void;
  autoCapitalize?: "none" | "sentences" | "words";
  returnKeyType?: "next" | "go" | "done" | "search" | "send";
  onSubmitEditing?: () => void;
  error?: string;
  big?: boolean;
  small?: boolean;
}>(function Field(
  { label, labelRight, value, onChange, placeholder, keyboardType, secure, showToggle,
    onToggleSecure, autoCapitalize, returnKeyType, onSubmitEditing, error, big, small },
  ref
) {
  const [focused, setFocused] = useState(false);
  return (
    <View style={[S.fieldWrap, big && S.fieldWrapBig, small && S.fieldWrapSmall]}>
      <View style={S.fieldLabelRow}>
        <Text style={[S.fieldLabel, big && S.fieldLabelBig, small && S.fieldLabelSmall]}>{label}</Text>
        {labelRight}
      </View>
      <View style={S.fieldInputWrap}>
        <TextInput
          ref={ref}
          style={[
            S.fieldInput,
            big && S.fieldInputBig,
            small && S.fieldInputSmall,
            focused && S.fieldInputFocused,
            !!error && S.fieldInputError,
            showToggle !== undefined && { paddingRight: 54 },
          ]}
          value={value}
          onChangeText={onChange}
          placeholder={placeholder}
          placeholderTextColor={C.gray400}
          keyboardType={keyboardType ?? "default"}
          secureTextEntry={!!secure && !showToggle}
          autoCapitalize={autoCapitalize ?? "sentences"}
          autoCorrect={false}
          returnKeyType={returnKeyType}
          onSubmitEditing={onSubmitEditing}
          blurOnSubmit={returnKeyType === "go" || returnKeyType === "done"}
          onFocus={() => setFocused(true)}
          onBlur={() => setFocused(false)}
        />
        {secure !== undefined && onToggleSecure && (
          <TouchableOpacity style={S.eyeBtn} onPress={onToggleSecure} activeOpacity={0.7}>
            <I.Eye visible={showToggle ?? false} c={error ? C.error500 : C.gray400} />
          </TouchableOpacity>
        )}
      </View>
      {!!error && <Text style={S.fieldError}>{error}</Text>}
    </View>
  );
});

// ── Screen ───────────────────────────────────────────────────────────────────

export default function LoginScreen() {
  const { isTablet, isLandscape, height } = useResponsive();
  const insets = useSafeAreaInsets();
  // Scale up the form on tablets (both orientations) so fields/text aren't tiny.
  const big = isTablet;
  // Phone in landscape: short screen → shrink text/controls below portrait size.
  const small = isLandscape && !isTablet;
  // Compact spacing on shorter phones so the form fits without scrolling.
  const compact = !isTablet && height < 760;

  const { user, signIn, signInWithGoogle, isLoading, error, clearError, resetPassword } = useAuth();
  const bio = useBiometricAuth();
  const [email, setEmail]                   = useState("");
  const [password, setPassword]             = useState("");
  const [showPassword, setShowPassword]     = useState(false);
  const [submitting, setSubmitting]         = useState(false);
  const [resetSent, setResetSent]           = useState(false);
  const [resetLoading, setResetLoading]     = useState(false);
  const [resetError, setResetError]         = useState("");
  const [emailError, setEmailError]         = useState("");
  const [passwordError, setPasswordError]   = useState("");

  const emailRef    = useRef<TextInput>(null);
  const passwordRef = useRef<TextInput>(null);

  // Only auto-focus on tablet — on mobile it opens the keyboard immediately
  // and scrolls past the brand header before the user sees it.
  useFocusEffect(
    useCallback(() => {
      if (!isTablet) return;
      const task = InteractionManager.runAfterInteractions(() => {
        emailRef.current?.focus();
      });
      return () => task.cancel();
    }, [isTablet])
  );

  useEffect(() => { if (error || user) setSubmitting(false); }, [error, user]);
  useEffect(() => {
    if (!submitting) return;
    const t = setTimeout(() => setSubmitting(false), 12000);
    return () => clearTimeout(t);
  }, [submitting]);

  const handleLogin = useCallback(async () => {
    if (submitting) return;

    const result = loginSchema.safeParse({ email: email.trim(), password });
    if (!result.success) {
      const { fieldErrors } = z.flattenError(result.error);
      setEmailError(fieldErrors.email?.[0] ?? "");
      setPasswordError(fieldErrors.password?.[0] ?? "");
      return;
    }
    setEmailError("");
    setPasswordError("");

    clearError();
    setResetSent(false);
    setSubmitting(true);
    await signIn(result.data.email.toLowerCase(), result.data.password);
  }, [email, password, signIn, clearError, submitting]);

  const handleBiometricLogin = useCallback(async () => {
    if (submitting || isLoading) return;
    clearError();
    setResetSent(false);
    setResetError("");
    setSubmitting(true);
    await bio.signIn();
  }, [submitting, isLoading, bio, clearError]);

  const handleForgotPassword = useCallback(async () => {
    const trimmed = email.trim();
    if (!trimmed) {
      setEmailError("Enter your email address first.");
      return;
    }
    if (resetLoading) return;
    setResetError("");
    setResetSent(false);
    setResetLoading(true);
    try {
      await resetPassword(trimmed);
      setResetSent(true);
    } catch (err: unknown) {
      const msg =
        errField(err, "code") === "auth/invalid-email"
          ? "Please enter a valid email address."
          : errField(err, "code") === "auth/user-not-found"
          ? "No account found for that email."
          : "Could not send reset email. Please try again.";
      setResetError(msg);
    } finally {
      setResetLoading(false);
    }
  }, [email, resetPassword, resetLoading]);

  const handleContactSupport = useCallback(() => {
    showAlert(
      "Merchant Support",
      "Need help signing in?\n\nEmail: support@lalaba.com\nHours: Mon–Sat, 8AM–8PM"
    );
  }, []);

  // ── Reusable JSX fragments ────────────────────────────────────────────────

  const forgotLink = (
    <TouchableOpacity onPress={handleForgotPassword} activeOpacity={0.7} disabled={resetLoading} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }} style={{ flexDirection: "row", alignItems: "center", gap: 4 }}>
      {resetLoading
        ? <ActivityIndicator size="small" color={C.brand500} />
        : <Text style={[S.forgotText, big && S.forgotTextBig, small && S.forgotTextSmall]}>Forgot password?</Text>}
    </TouchableOpacity>
  );

  // Core login form — goes inside the card for all layouts
  const errorBanner = error ? (
    <View style={S.errorBanner}>
      <Text style={S.errorText}>{error}</Text>
    </View>
  ) : null;
  const formCore = (
    <>
      {resetSent ? (
        <View style={S.successBanner}>
          <Text style={S.successText}>Reset link sent! Check your email inbox.</Text>
          <TouchableOpacity onPress={handleForgotPassword} disabled={resetLoading} style={{ marginTop: 4 }}>
            {resetLoading
              ? <ActivityIndicator size="small" color={C.brand600} />
              : <Text style={[S.successText, { textDecorationLine: "underline", fontWeight: "600" }]}>Resend</Text>}
          </TouchableOpacity>
        </View>
      ) : resetError ? (
        <View style={S.errorBanner}>
          <Text style={S.errorText}>{resetError}</Text>
        </View>
      ) : errorBanner}

      <Field
        ref={emailRef}
        label="Email Address"
        value={email}
        onChange={(v) => { setEmail(v); if (emailError) setEmailError(""); if (resetError) setResetError(""); }}
        placeholder="merchant@example.com"
        keyboardType="email-address"
        autoCapitalize="none"
        returnKeyType="next"
        onSubmitEditing={() => passwordRef.current?.focus()}
        error={emailError}
        big={big}
        small={small}
      />

      <Field
        ref={passwordRef}
        label="Password"
        labelRight={forgotLink}
        value={password}
        onChange={(v) => { setPassword(v); if (passwordError) setPasswordError(""); }}
        placeholder="Enter your password"
        secure
        showToggle={showPassword}
        onToggleSecure={() => setShowPassword(v => !v)}
        returnKeyType="go"
        onSubmitEditing={handleLogin}
        error={passwordError}
        big={big}
        small={small}
      />

      <TouchableOpacity
        style={[S.signInBtn, big && S.signInBtnBig, small && S.signInBtnSmall, (isLoading || submitting || !email.trim() || !password) && S.signInBtnDisabled]}
        onPress={handleLogin}
        disabled={isLoading || submitting || !email.trim() || !password}
        activeOpacity={0.8}
      >
        {(isLoading || submitting)
          ? <ActivityIndicator color={C.white} />
          : (
            <Text style={[
              S.signInBtnText, big && S.signInBtnTextBig, small && S.signInBtnTextSmall,
              (!email.trim() || !password) && S.signInBtnTextDisabled,
            ]}>Sign In</Text>
          )}
      </TouchableOpacity>

      {/* Biometric sign-in — only when a credential is enrolled on this device */}
      {bio.available && bio.enrolled && (
        <TouchableOpacity
          style={{
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            gap: 8,
            marginTop: 12,
            paddingVertical: small ? 11 : 14,
            borderRadius: 12,
            borderWidth: 1.5,
            borderColor: C.brand500,
            backgroundColor: C.brand50,
            opacity: isLoading || submitting ? 0.6 : 1,
          }}
          onPress={handleBiometricLogin}
          disabled={isLoading || submitting}
          activeOpacity={0.8}
          accessibilityRole="button"
          accessibilityLabel={`Sign in with ${bio.label}`}
        >
          {bio.biometryType === "FaceID" ? <I.FaceId /> : <I.Fingerprint />}
          <Text style={{ color: C.brand600, fontWeight: "700", fontSize: small ? 14 : 15 }}>
            Sign in with {bio.label.charAt(0).toUpperCase() + bio.label.slice(1)}
          </Text>
        </TouchableOpacity>
      )}

    </>
  );

  // Social login — below the card on mobile, inside the card on tablet
  const socialLogin = (
    <>
      <View style={[S.divider, small && S.dividerSmall]}>
        <View style={S.dividerLine} />
        <Text style={[S.dividerText, big && S.dividerTextBig, small && S.dividerTextSmall]}>or</Text>
        <View style={S.dividerLine} />
      </View>

      <TouchableOpacity
        style={[S.googleBtn, big && S.googleBtnBig, small && S.googleBtnSmall, (isLoading || submitting) && { opacity: 0.6 }]}
        onPress={signInWithGoogle}
        disabled={isLoading || submitting}
        activeOpacity={0.8}
      >
        <I.Google />
        <Text style={[S.googleBtnText, big && S.googleBtnTextBig, small && S.googleBtnTextSmall]}>Continue with Google</Text>
      </TouchableOpacity>

      <TouchableOpacity
        style={[S.appleBtn, big && S.appleBtnBig, small && S.appleBtnSmall, { opacity: 0.5 }]}
        disabled
        accessibilityRole="button"
        accessibilityState={{ disabled: true }}
        activeOpacity={0.8}
      >
        <I.Apple />
        <Text style={[S.appleBtnText, big && S.appleBtnTextBig, small && S.appleBtnTextSmall]}>Continue with Apple</Text>
      </TouchableOpacity>
    </>
  );

  // Combined — used by tablet layouts
  const formContent = <>{formCore}{socialLogin}</>;


  const cardHeader = () => (
    <>
      <Text style={[S.cardTitle, small && S.cardTitleSmall]}>Welcome back</Text>
      <Text style={[S.cardSub, small && S.cardSubSmall]}>Sign in to manage your orders and shop operations.</Text>
    </>
  );

  const registerLink = (dark = false) => (
    <TouchableOpacity onPress={() => router.push("/register")} activeOpacity={0.7} style={S.registerRow}>
      <Text style={dark ? S.registerTextDark : S.registerText}>
        New to Lalaba Partner?{" "}
        <Text style={dark ? S.registerLinkDark : S.registerLink}>Create your account</Text>
      </Text>
    </TouchableOpacity>
  );

  const supportLink = (dark = false) => (
    <TouchableOpacity onPress={handleContactSupport} activeOpacity={0.7} style={S.supportRow}>
      <Text style={dark ? S.supportTextDark : S.supportText}>
        Need help signing in?{" "}
        <Text style={dark ? S.supportLinkDark : S.supportLink}>Contact support</Text>
      </Text>
    </TouchableOpacity>
  );

  // Build version footer — shown across all layouts
  const versionFooter = <Text style={S.versionText}>v{APP_VERSION}</Text>;

  // ── Landscape (phone + tablet) ────────────────────────────────────────────
  // Any device in landscape uses the split-pane layout; the mobile hero layout
  // below is portrait-only.
  if (isLandscape) {
    // Each panel owns its own top/bottom safe-area padding so its background
    // color reaches the true screen edge — a shared SafeAreaView around both
    // panels would inset the whole row and expose S.safe's blue behind the
    // white panel, reading as a border instead of a clean 40/60 split.
    const brandVPad = small ? 16 : 40;
    const panelVPad = small ? 20 : 40;
    return (
      <View style={S.safe}>
        <LoadingOverlay visible={submitting} label="Signing in…" />
        <KeyboardAvoidingView style={S.flex} behavior="padding">
          <View style={S.lsRoot}>

            {/* ── Left brand panel (40%) ── */}
            <View style={[
              S.lsBrand, small && S.lsBrandSmall,
              { paddingTop: brandVPad + insets.top, paddingBottom: brandVPad + insets.bottom },
            ]}>
              <Image source={LOGO} style={[S.lsLogo, small && S.lsLogoSmall]} resizeMode="contain" />
              <Text style={[S.lsTagline, small && S.lsTaglineSmall]}>Your Business,{"\n"}Our Technology</Text>
              <Text style={[S.lsTaglineSub, small && S.lsTaglineSubSmall]}>
                Manage orders, payments, staff,{"\n"}and shop activity — all in one place.
              </Text>

              <View style={[S.statStack, small && S.statStackSmall]}>
                <StatCard icon={<I.Package />} label="Today's Active Orders" value="24 Orders" small={small} />
                <StatCard icon={<I.Receipt />} label="Monthly Revenue" value="₱12,450" small={small} />
              </View>
            </View>

            {/* ── Right form panel (60%) ── */}
            <ScrollView
              style={S.lsPanel}
              contentContainerStyle={[
                S.lsPanelContent, small && S.lsPanelContentSmall,
                { paddingTop: panelVPad + insets.top, paddingBottom: panelVPad + insets.bottom },
              ]}
              keyboardShouldPersistTaps="handled"
              showsVerticalScrollIndicator={false}
            >
              <View style={S.lsCard}>
                {cardHeader()}
                {formContent}
                {registerLink()}
                {supportLink()}
                {versionFooter}
              </View>
            </ScrollView>

          </View>
        </KeyboardAvoidingView>
      </View>
    );
  }

  // ── Tablet portrait ───────────────────────────────────────────────────────
  // GCash-style: the card fills the screen with margins on all four sides
  // (ResponsivePage `fill`), and the form is centered at a readable width.
  if (isTablet && !isLandscape) {
    return (
      <>
        <LoadingOverlay visible={submitting} label="Signing in…" />
        <ResponsivePage fill edges={["top", "bottom"]}>
          <View style={S.tpCard}>
            <View style={S.tpFormWrap}>
              <Image source={LOGO} style={S.tpLogo} resizeMode="contain" />
              {cardHeader()}
              {formContent}
              {registerLink()}
              {supportLink()}
              {versionFooter}
            </View>
          </View>
        </ResponsivePage>
      </>
    );
  }

  // ── Mobile ────────────────────────────────────────────────────────────────
  return (
    <SafeAreaView style={S.safe} edges={["top", "bottom"]}>
      <LoadingOverlay visible={submitting} label="Signing in…" />

      {/* Blue brand hero */}
      <View style={[S.mobBrand, compact && S.mobBrandCompact]}>
        <Image source={LOGO} style={[S.mobLogo, compact && S.mobLogoCompact]} resizeMode="contain" />
        <Text style={S.mobTagline}>Your Business, Our Technology</Text>
      </View>

      {/* White sheet — KAV wraps only the form area */}
      <KeyboardAvoidingView style={S.mobSheet} behavior="padding">
        <ScrollView
          contentContainerStyle={S.mobSheetContent}
          keyboardShouldPersistTaps="handled"
          showsVerticalScrollIndicator={false}
        >
          <Text style={S.mobTitle}>Sign in to your account</Text>
          <Text style={S.mobSub}>Enter your credentials to continue.</Text>
          {formCore}
          {socialLogin}
          {/* Spacer pushes the footer details down to fill the bottom space */}
          <View style={S.mobSpacer} />
          {registerLink()}
          {supportLink()}
          {versionFooter}
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}
